export const PATHS = {
  HOME: "/",
  HOROSCOPE: "/horoscope",
  KUNDALI_MATCHING: "/kundali-matching",
  NAKSHATRA_MILAN: "/nakshatra-milan",
  KUNDALI_MATCHING_BY_NAME: "/kundali-matching-by-name",
  MANGAL_DOSHA: "/mangal-dosha",
  KAAL_SARP_DOSH: "/kaal-sarp-dosh",
  LOVE_CALCULATOR: "/love-calculator",
  SUN_SIGN: "/sun-sign",
  MOON_SIGN: "/moon-sign",
  NAKSHATRA: "/nakshatra",
  BUY_PRODUCTS: "/buy-products",
  FREE_SERVICES: "/free-services",
  ONLINE_PUJA: "/online-puja",
  CART: "/cart",
  CHECKOUT: "/checkout",
  PROFILE: "/profile",
  SIGN_IN: "/sign-in",
  REGISTER: "/register",
  HELP: "/help",
  SESSION_HISTORY: "/session-history",
  FAMOUS_PLACES: "/famous-places",
  BLOG: "/blog",

  WALLET: "/wallet",

  // FREE CALCULATORS
  PLANET: "/calculator/planet",
  FLAMES_CALCULATOR: "/calculator/flames",
  LOVE_COMPATIBILITY_CALCULATOR: "/calculator/love-compatibility",
  MARRIAGE_AGE_CALCULATOR: "/calculator/marriage-age",
  SOULMATE_NAME_INITALS_CALCULATOR: "/calculator/soulmate-name-initials",
  LUCKY_NUMBER_CALCULATOR: "/calculator/lucky-number",
  LUCKY_COLOR_CALCULATOR: "/calculator/lucky-color",
  LIFE_PATH_CALCULATOR: "/calculator/life-path",
  NAME_NUMEROLOGY_CALCULATOR: "/calculator/name-numerology",
  ZODIAC_SIGN_CALCULATOR: "/calculator/zodiac-sign-compatibility",
  NAKSHATRA_FINDER: "/calculator/nakshatra-finder",
  LOYAL_PARTNER_CALCULATOR: "/calculator/loyal-partner",
  BREAKUP_PATCHUP_CALCULATOR: "/calculator/breakup-patchup",
  WHO_LOVES_MORE_CALCULATOR: "/calculator/who-loves-more",
  COMPATIBILITY_BY_ZODIAC_CALCULATOR: "/calculator/compatibility-by-zodiac",

} as const;
