export const PATHS = {
  HOME: "/",
  HOROSCOPE: "/horoscope",
  KUNDALI_MATCHING: "/kundali-matching",
  NAKSHATRA_MILAN: "/nakshatra-milan",
  KUNDALI_MATCHING_BY_NAME: "/kundali-matching-by-name",
  MANGAL_DOSHA: "/mangal-dosha",
  KAAL_SARP_DOSH: "/kaal-sarp-dosh",
  LOVE_CALCULATOR: "/love-calculator",
  SUN_SIGN: "/sun-sign",
  MOON_SIGN: "/moon-sign",
  NAKSHATRA: "/nakshatra",
  BUY_PRODUCTS: "/buy-products",
  FREE_SERVICES: "/free-services",
  ONLINE_PUJA: "/online-puja",
  CART: "/cart",
  CHECKOUT: "/checkout",
  PROFILE: "/profile",
  SIGN_IN: "/sign-in",
  REGISTER: "/register",
  HELP: "/help",
  SESSION_HISTORY: "/session-history",
  FAMOUS_PLACES: "/famous-places",
  BLOG: "/blog",
  WALLET: "/wallet",
} as const;
