import { ProductGroup, ProductType, ExpertProductRelationType } from "@repo/lib";
import { RemedyItem, RemedyTabConfig, RemedyTabKey } from "./types";

export const REMEDY_TABS_CONFIG: RemedyTabConfig[] = [
  {
    key: "reports",
    label: "Astrology Reports",
    shortLabel: "Reports",
    sublabel: "Kundli & Predictions",
    productGroup: ProductGroup.REPORT,
    description:
      "Handcrafted Vedic birth chart calculations, planetary dosha analysis, and customized remedies prepared by certified astrologers.",
    highlightTag: "Comprehensive PDF & Audio Reports",
  },
  {
    key: "rituals",
    label: "Puja, Havan & Rituals",
    shortLabel: "Puja & Havan",
    sublabel: "Vedic Ceremonies",
    productGroup: ProductGroup.RITUAL,
    description:
      "Authentic Vedic rituals performed by learned karmkandi pandits with individual Sankalp in your Gotra, with live video stream and sacred Prasad.",
    highlightTag: "Live Sankalp & Prasad Delivery",
  },
  {
    key: "gemstones",
    label: "Mala & Gemstones",
    shortLabel: "Mala & Gems",
    sublabel: "100% Certified",
    productGroup: ProductGroup.ITEM,
    description:
      "100% lab-certified natural gemstones and authentic Rudraksha malas energized (Abhimantrit) with sacred planetary Vedic Beej Mantras.",
    highlightTag: "Lab Certified & Energized",
  },
  {
    key: "books",
    label: "Books & Old Texts",
    shortLabel: "Books & Texts",
    sublabel: "Sacred Granthas",
    productGroup: ProductGroup.BOOK,
    description:
      "Classical Vedic astrology scriptures, Lal Kitab remedial treatises, and sacred spiritual texts with authentic Sanskrit shlokas and translations.",
    highlightTag: "Authentic Ancient Scriptures",
  },
  {
    key: "consultations",
    label: "Specialized Consultations",
    shortLabel: "30m / 60m Sessions",
    sublabel: "Dedicated Private Calls",
    productGroup: ProductGroup.SESSION,
    description:
      "Book a dedicated 30-minute laser problem-solving call or a 60-minute comprehensive birth chart blueprint session with direct 1-on-1 access.",
    highlightTag: "Dedicated 1-on-1 Audio/Video",
  },
];

export const CURATED_REMEDIES: Record<RemedyTabKey, RemedyItem[]> = {
  reports: [
    {
      id: "rep-1",
      name: "Complete Janam Kundli & Life Blueprint",
      slug: "complete-janam-kundli-life-blueprint",
      categoryName: "Astrology Reports",
      description:
        "100+ pages of in-depth Vedic analysis covering your ascendant, divisional charts, Vimshottari Dasha, career roadmap, and life remedies.",
      shortDescription:
        "Exhaustive 100+ pages Vedic life forecast with customized gemstone and mantra remedies.",
      productGroup: ProductGroup.REPORT,
      productType: ProductType.DIGITAL,
      price: 999,
      originalPrice: 2499,
      discountPercent: 60,
      rating: 4.9,
      reviewCount: 342,
      imageUrl: "/images/kundli-bg-elegant.jpg",
      features: ["100+ Pages PDF", "20-Year Dasha Analysis", "Custom Remedies", "24-Hour Delivery"],
      durationOrPages: "100+ Pages PDF",
      badgeText: "Most Popular",
      isPopular: true,
      ctaText: "Get Report",
      ctaLink: "/shop/rep-1",
      relationType: ExpertProductRelationType.PROMOTER,
      inStock: true,
    },
    {
      id: "rep-2",
      name: "2026-2027 Annual Vedic Life & Career Forecast",
      slug: "annual-vedic-life-career-forecast-2026",
      categoryName: "Astrology Reports",
      description:
        "Month-by-month predictive breakdown covering planetary transits (Jupiter, Saturn, Rahu-Ketu), career promotions, investments, and health.",
      shortDescription:
        "Detailed month-by-month astrological forecast for the upcoming 12 months.",
      productGroup: ProductGroup.REPORT,
      productType: ProductType.DIGITAL,
      price: 1499,
      originalPrice: 2999,
      discountPercent: 50,
      rating: 4.8,
      reviewCount: 218,
      imageUrl: "/images/kundli-bg-softglow.jpg",
      features: ["Month-by-Month Guide", "Transit Impact Analysis", "Financial Timing", "Instant Download"],
      durationOrPages: "45 Pages PDF",
      badgeText: "Yearly Special",
      ctaText: "Get Report",
      ctaLink: "/shop/rep-2",
      relationType: ExpertProductRelationType.PROVIDER,
      inStock: true,
    },
    {
      id: "rep-3",
      name: "Kundli Milan & Marriage Compatibility Report",
      slug: "kundli-milan-marriage-compatibility-report",
      categoryName: "Astrology Reports",
      description:
        "Complete 36 Guna Milan analysis, Manglik Dosha exceptions, Nadi Dosha evaluation, Bhakoot compatibility, and relationship remedies.",
      shortDescription:
        "Thorough 36 Guna matching and Manglik Dosha evaluation for prospective couples.",
      productGroup: ProductGroup.REPORT,
      productType: ProductType.DIGITAL,
      price: 799,
      originalPrice: 1800,
      discountPercent: 55,
      rating: 4.9,
      reviewCount: 189,
      imageUrl: "/images/kundli-matching-clean.jpg",
      features: ["Ashtakoot Guna Milan", "Manglik Dosha Check", "Remedy Suggestions", "Bilingual PDF"],
      durationOrPages: "35 Pages PDF",
      badgeText: "Recommended",
      ctaText: "Get Report",
      ctaLink: "/shop/rep-3",
      relationType: ExpertProductRelationType.PROMOTER,
      inStock: true,
    },
    {
      id: "rep-4",
      name: "Navgrah Dosha, Sade Sati & Remedial Guide",
      slug: "navgrah-dosha-sade-sati-remedial-guide",
      categoryName: "Astrology Reports",
      description:
        "Identify afflicted planets, Rahu-Ketu axis blockages, Sade Sati phases, and receive precise gemstone, Rudraksha, and daan recommendations.",
      shortDescription:
        "Comprehensive diagnosis of planetary afflictions with clear, actionable remedial upayas.",
      productGroup: ProductGroup.REPORT,
      productType: ProductType.DIGITAL,
      price: 899,
      originalPrice: 1999,
      discountPercent: 55,
      rating: 4.8,
      reviewCount: 154,
      imageUrl: "/images/horoscope-bg-softglow.jpg",
      features: ["Sade Sati Timeline", "Affliction Diagnosis", "Mantra & Daan Guide", "Gemstone Chart"],
      durationOrPages: "40 Pages PDF",
      badgeText: "Vedic Upayas",
      ctaText: "Get Report",
      ctaLink: "/shop/rep-4",
      relationType: ExpertProductRelationType.PROVIDER,
      inStock: true,
    },
  ],

  rituals: [
    {
      id: "rit-1",
      name: "Navgrah Shanti Maha Havan (9-Planet Balancing)",
      slug: "navgrah-shanti-maha-havan",
      categoryName: "Puja, Havan & Rituals",
      description:
        "Sacred Vedic fire ritual conducted by 3 experienced karmkandi pandits with authentic samagri and personalized Sankalp for all 9 planetary lords.",
      shortDescription:
        "Comprehensive 9-planet balancing havan to alleviate malefic influences and invite peace.",
      productGroup: ProductGroup.RITUAL,
      productType: ProductType.SERVICE,
      price: 3501,
      originalPrice: 5100,
      discountPercent: 31,
      rating: 4.9,
      reviewCount: 420,
      imageUrl: "/images/online-puja-banner.png",
      features: ["Live Video Stream", "Personal Gotra Sankalp", "Prasad Courier Included", "3 Vedic Pandits"],
      durationOrPages: "2.5 Hours Ritual",
      badgeText: "High Demand",
      isPopular: true,
      ctaText: "Book Puja",
      ctaLink: "/puja",
      relationType: ExpertProductRelationType.PROVIDER,
      inStock: true,
    },
    {
      id: "rit-2",
      name: "Maha Mrityunjaya Jaap & Anushthan (11,000 Jaap)",
      slug: "maha-mrityunjaya-jaap-anushthan",
      categoryName: "Puja, Havan & Rituals",
      description:
        "Powerful life-protecting chanting ritual performed by Vedic scholars for health restoration, longevity, and shielding against negative planetary energies.",
      shortDescription:
        "Sacred 11,000 Maha Mrityunjaya mantra chants for vitality, recovery, and long life.",
      productGroup: ProductGroup.RITUAL,
      productType: ProductType.SERVICE,
      price: 5100,
      originalPrice: 7500,
      discountPercent: 32,
      rating: 5.0,
      reviewCount: 295,
      imageUrl: "/images/famous-temples-banner.png",
      features: ["11,000 Vedic Chants", "Audio & Video Recording", "Energized Raksha Sutra", "Personalized Sankalp"],
      durationOrPages: "3.5 Hours Ritual",
      badgeText: "Health & Longevity",
      ctaText: "Book Puja",
      ctaLink: "/puja",
      relationType: ExpertProductRelationType.PROMOTER,
      inStock: true,
    },
    {
      id: "rit-3",
      name: "Kaal Sarp Dosh Nivaran Sacred Puja",
      slug: "kaal-sarp-dosh-nivaran-sacred-puja",
      categoryName: "Puja, Havan & Rituals",
      description:
        "Specialized Vedic ritual to neutralize the 12 variants of Kaal Sarp Dosha, removing sudden delays, career roadblocks, and mental stress.",
      shortDescription:
        "Neutralizes Rahu-Ketu planetary dosha to clear blocked career paths and life progress.",
      productGroup: ProductGroup.RITUAL,
      productType: ProductType.SERVICE,
      price: 4100,
      originalPrice: 6000,
      discountPercent: 31,
      rating: 4.8,
      reviewCount: 168,
      imageUrl: "/images/why-choose-puja-banner.png",
      features: ["Silver Snake Offering", "Rahu-Ketu Shanti", "Live HD Broadcast", "Energized Yantra Included"],
      durationOrPages: "2 Hours Ritual",
      badgeText: "Dosha Nivaran",
      ctaText: "Book Puja",
      ctaLink: "/puja",
      relationType: ExpertProductRelationType.PROVIDER,
      inStock: true,
    },
    {
      id: "rit-4",
      name: "Mangal Dosh Shanti & Maha Rudrabhishek",
      slug: "mangal-dosh-shanti-rudrabhishek",
      categoryName: "Puja, Havan & Rituals",
      description:
        "Traditional Panchamrit Rudrabhishek for Lord Shiva to pacify an aggressive Mars (Mangal), resolving relationship discord and delay in marriage.",
      shortDescription:
        "Sacred Panchamrit abhishek on Shivling for marital peace, delay removal, and temperament balance.",
      productGroup: ProductGroup.RITUAL,
      productType: ProductType.SERVICE,
      price: 2999,
      originalPrice: 4500,
      discountPercent: 33,
      rating: 4.9,
      reviewCount: 210,
      imageUrl: "/images/kashi.jpg",
      features: ["Panchamrit Abhishek", "Live Darshan", "Vibhuti & Bhasma Prasad", "Dedicated Pandit"],
      durationOrPages: "1.5 Hours Ritual",
      badgeText: "Marital Peace",
      ctaText: "Book Puja",
      ctaLink: "/puja",
      relationType: ExpertProductRelationType.PROMOTER,
      inStock: true,
    },
  ],

  gemstones: [
    {
      id: "gem-1",
      name: "Certified Natural Yellow Sapphire (Pukhraj) 5.25 Ratti",
      slug: "certified-natural-yellow-sapphire-pukhraj",
      categoryName: "Mala & Gemstones",
      description:
        "100% untreated Ceylon natural gemstone certified by Govt. approved laboratory. Energized with Jupiter (Guru) Vedic rituals for wisdom and wealth.",
      shortDescription:
        "Lab-certified natural Ceylon Yellow Sapphire for wealth, marriage, and spiritual wisdom.",
      productGroup: ProductGroup.ITEM,
      productType: ProductType.GOODS,
      price: 12500,
      originalPrice: 18000,
      discountPercent: 30,
      rating: 4.9,
      reviewCount: 175,
      imageUrl: "/images/ser3.jpg",
      features: ["Govt. Lab Certificate", "Vedic Abhimantrit", "Free Silver Ring Mounting", "100% Natural"],
      durationOrPages: "5.25 Ratti",
      badgeText: "100% Certified",
      isPopular: true,
      ctaText: "Order Gemstone",
      ctaLink: "/shop/gem-1",
      relationType: ExpertProductRelationType.PROVIDER,
      inStock: true,
    },
    {
      id: "gem-2",
      name: "Authentic 5-Mukhi Nepali Rudraksha Mala (108+1 Beads)",
      slug: "authentic-5-mukhi-nepali-rudraksha-mala",
      categoryName: "Mala & Gemstones",
      description:
        "Original hand-knotted Nepali Rudraksha beads (8mm) blessed for peace of mind, blood pressure balance, deep meditation, and negative energy shield.",
      shortDescription:
        "Hand-knotted 108+1 natural Nepali Rudraksha mala energized with Lord Shiva mantras.",
      productGroup: ProductGroup.ITEM,
      productType: ProductType.GOODS,
      price: 1299,
      originalPrice: 2499,
      discountPercent: 48,
      rating: 4.9,
      reviewCount: 530,
      imageUrl: "/images/ser5.jpg",
      features: ["108+1 Nepali Beads", "Lab Tested Authenticity", "Energized with Gangajal", "Velvet Pouch Included"],
      durationOrPages: "108+1 Beads",
      badgeText: "Best Seller",
      ctaText: "Order Mala",
      ctaLink: "/shop/gem-2",
      relationType: ExpertProductRelationType.PROMOTER,
      inStock: true,
    },
    {
      id: "gem-3",
      name: "Siddh 24K Gold-Plated Shree Yantra with Wooden Base",
      slug: "siddh-24k-gold-plated-shree-yantra",
      categoryName: "Mala & Gemstones",
      description:
        "Sacred geometric cosmic diagram engraved with precision and energized through Vedic Prana Pratishtha for prosperity, abundance, and Vastu harmony.",
      shortDescription:
        "Sacred energized geometric Yantra to attract wealth, positive vibrations, and family peace.",
      productGroup: ProductGroup.ITEM,
      productType: ProductType.GOODS,
      price: 2199,
      originalPrice: 3999,
      discountPercent: 45,
      rating: 4.8,
      reviewCount: 240,
      imageUrl: "/images/ser7.jpg",
      features: ["24K Gold Plating", "Prana Pratishtha Done", "Teakwood Base", "Vastu Cleansing Guide"],
      durationOrPages: "6x6 Inches",
      badgeText: "Prosperity",
      ctaText: "Order Yantra",
      ctaLink: "/shop/gem-3",
      relationType: ExpertProductRelationType.PROVIDER,
      inStock: true,
    },
    {
      id: "gem-4",
      name: "Natural Blue Sapphire (Neelam) Certified 4.25 Ratti",
      slug: "natural-blue-sapphire-neelam-certified",
      categoryName: "Mala & Gemstones",
      description:
        "Premium unheated blue sapphire gemstone of astrological quality. Prescribed for individuals under favorable Saturn (Shani) Mahadasha.",
      shortDescription:
        "Lab-certified authentic Saturn gemstone for quick career breakthroughs and discipline.",
      productGroup: ProductGroup.ITEM,
      productType: ProductType.GOODS,
      price: 15999,
      originalPrice: 22000,
      discountPercent: 27,
      rating: 5.0,
      reviewCount: 88,
      imageUrl: "/images/ser9.jpg",
      features: ["Govt. Lab Certificate", "Astrological Grade", "Untreated & Unheated", "Custom Astrological Fit"],
      durationOrPages: "4.25 Ratti",
      badgeText: "Premium Grade",
      ctaText: "Order Gemstone",
      ctaLink: "/shop/gem-4",
      relationType: ExpertProductRelationType.PROVIDER,
      inStock: true,
    },
  ],

  books: [
    {
      id: "book-1",
      name: "Brihat Parashara Hora Shastra (2 Volumes Sanskrit & Hindi)",
      slug: "brihat-parashara-hora-shastra-2-volumes",
      categoryName: "Books & Old Texts",
      description:
        "The definitive foundational encyclopedia of Vedic astrology containing Maharishi Parashara's original shlokas, detailed bhavas, yogas, and dasha rules.",
      shortDescription:
        "The ultimate classical treatise on Vedic astrology with authentic Sanskrit slokas and Hindi commentary.",
      productGroup: ProductGroup.BOOK,
      productType: ProductType.GOODS,
      price: 1850,
      originalPrice: 2500,
      discountPercent: 26,
      rating: 5.0,
      reviewCount: 310,
      imageUrl: "/images/ser11.jpg",
      features: ["Hardcover 2-Vol Set", "Original Sanskrit Shlokas", "Clear Hindi Translation", "1200+ Pages"],
      durationOrPages: "Hardcover 2-Vol",
      badgeText: "Foundational Classic",
      isPopular: true,
      ctaText: "Buy Book",
      ctaLink: "/shop/book-1",
      relationType: ExpertProductRelationType.PROVIDER,
      inStock: true,
    },
    {
      id: "book-2",
      name: "Lal Kitab - Original 1952 Remedial Scripture (Hindi)",
      slug: "lal-kitab-original-remedial-scripture-hindi",
      categoryName: "Books & Old Texts",
      description:
        "The complete authentic guide to unique planetary totkas, house-by-house afflictions, and practical daily remedies requiring no complex rituals.",
      shortDescription:
        "Authentic edition of the famous Lal Kitab with simple, highly effective self-remedies.",
      productGroup: ProductGroup.BOOK,
      productType: ProductType.GOODS,
      price: 999,
      originalPrice: 1500,
      discountPercent: 33,
      rating: 4.8,
      reviewCount: 420,
      imageUrl: "/images/ser12.jpg",
      features: ["Practical Upayas", "House-by-House Remedies", "Detailed Explanations", "Hindi Edition"],
      durationOrPages: "580 Pages",
      badgeText: "Remedies Classic",
      ctaText: "Buy Book",
      ctaLink: "/shop/book-2",
      relationType: ExpertProductRelationType.PROMOTER,
      inStock: true,
    },
    {
      id: "book-3",
      name: "Phaladeepika by Mantreswara (Sacred Predictive Astrology)",
      slug: "phaladeepika-mantreswara-predictive-astrology",
      categoryName: "Books & Old Texts",
      description:
        "A revered classical manual detailing planetary yogas, transit outcomes (Gochar), longevity calculations, and bhava analysis with immense precision.",
      shortDescription:
        "Revered classical text for mastering accurate astrological predictions and transit analysis.",
      productGroup: ProductGroup.BOOK,
      productType: ProductType.GOODS,
      price: 750,
      originalPrice: 1100,
      discountPercent: 31,
      rating: 4.9,
      reviewCount: 165,
      imageUrl: "/images/ser14.jpg",
      features: ["Predictive Techniques", "Transit (Gochar) Rules", "Raja Yoga Chapters", "Paperback"],
      durationOrPages: "430 Pages",
      badgeText: "Predictions",
      ctaText: "Buy Book",
      ctaLink: "/shop/book-3",
      relationType: ExpertProductRelationType.PROVIDER,
      inStock: true,
    },
    {
      id: "book-4",
      name: "Saravali by Kalyana Varma (Royal Yogas & Life Predictions)",
      slug: "saravali-kalyana-varma-royal-yogas",
      categoryName: "Books & Old Texts",
      description:
        "Comprehensive classical text summarizing ancient teachings on planetary states, birth yogas, female horoscopy, and vocational astrology.",
      shortDescription:
        "Master classical reference on planetary strength, royal combinations, and character analysis.",
      productGroup: ProductGroup.BOOK,
      productType: ProductType.GOODS,
      price: 1150,
      originalPrice: 1600,
      discountPercent: 28,
      rating: 4.8,
      reviewCount: 118,
      imageUrl: "/images/ser16.jpg",
      features: ["Detailed Yogas", "Sanskrit & Hindi Meaning", "Planetary Strengths", "Durable Binding"],
      durationOrPages: "620 Pages",
      badgeText: "Classical Text",
      ctaText: "Buy Book",
      ctaLink: "/shop/book-4",
      relationType: ExpertProductRelationType.PROMOTER,
      inStock: true,
    },
  ],

  consultations: [
    {
      id: "sess-1",
      name: "30-Minute Focused Laser Consultation",
      slug: "30-minute-focused-laser-consultation",
      categoryName: "Specialized Consultations",
      description:
        "Private 1-on-1 direct phone or video call with direct analysis of 1-2 pressing problems: career choice, relationship dilemma, job switch, or health concern.",
      shortDescription:
        "Direct 30-minute private audio/video consultation for instant clarity and targeted remedies.",
      productGroup: ProductGroup.SESSION,
      productType: ProductType.SERVICE,
      price: 799,
      originalPrice: 1500,
      discountPercent: 46,
      rating: 4.9,
      reviewCount: 680,
      imageUrl: "/images/horoscope-bg-elegant.jpg",
      features: ["30 Minutes 1-on-1 Call", "Direct Problem Solving", "Actionable Remedies Prescribed", "Session Summary Shared"],
      durationOrPages: "30 Mins Live Session",
      badgeText: "Most Booked",
      isPopular: true,
      ctaText: "Book 30m Session",
      ctaLink: "/chat",
      relationType: ExpertProductRelationType.PROVIDER,
      inStock: true,
    },
    {
      id: "sess-2",
      name: "60-Minute Comprehensive Life & Kundli Blueprint",
      slug: "60-minute-comprehensive-life-kundli-blueprint",
      categoryName: "Specialized Consultations",
      description:
        "Deep-dive 1-hour consultation examining your Janam Kundli, Navamsha (D9), Dashamsha (D10), Vimshottari dasha, and custom remedial strategy.",
      shortDescription:
        "In-depth 60-minute private session covering full chart analysis, 5-year outlook, and remedies.",
      productGroup: ProductGroup.SESSION,
      productType: ProductType.SERVICE,
      price: 1499,
      originalPrice: 2800,
      discountPercent: 46,
      rating: 5.0,
      reviewCount: 490,
      imageUrl: "/images/kundli-bg-softglow.jpg",
      features: ["60 Minutes In-Depth Call", "Full Dasha & Chart Audit", "Custom Gemstone & Daan Plan", "Full Kundli Chart Included"],
      durationOrPages: "60 Mins Deep Dive",
      badgeText: "Highest Value",
      isPopular: true,
      ctaText: "Book 1-Hour Session",
      ctaLink: "/chat",
      relationType: ExpertProductRelationType.PROVIDER,
      inStock: true,
    },
    {
      id: "sess-3",
      name: "30-Minute Prashna Kundli & Urgent Remedy Session",
      slug: "30-minute-prashna-kundli-urgent-remedy-session",
      categoryName: "Specialized Consultations",
      description:
        "Instant horary chart casting for exact time of query. Perfect for immediate decisions like court cases, property deals, exams, or missing items.",
      shortDescription:
        "Time-tested Prashna Kundli session for urgent question resolution without exact birth time.",
      productGroup: ProductGroup.SESSION,
      productType: ProductType.SERVICE,
      price: 899,
      originalPrice: 1600,
      discountPercent: 43,
      rating: 4.8,
      reviewCount: 220,
      imageUrl: "/images/horoscope-bg-dark.jpg",
      features: ["No Exact Birth Time Needed", "Immediate Accurate Answers", "Urgent Decision Support", "Instant Remedial Upayas"],
      durationOrPages: "30 Mins Horary",
      badgeText: "Immediate Clarity",
      ctaText: "Book Prashna Session",
      ctaLink: "/chat",
      relationType: ExpertProductRelationType.PROMOTER,
      inStock: true,
    },
    {
      id: "sess-4",
      name: "60-Minute Couple Compatibility & Kundli Milan Audit",
      slug: "60-minute-couple-compatibility-kundli-milan-audit",
      categoryName: "Specialized Consultations",
      description:
        "Private 1-hour session with both charts reviewed side-by-side. Includes planetary dosha remedies, parental compatibility, and auspicious muhurats.",
      shortDescription:
        "60-minute dedicated couple session analyzing both birth charts and marital harmony upayas.",
      productGroup: ProductGroup.SESSION,
      productType: ProductType.SERVICE,
      price: 1999,
      originalPrice: 3500,
      discountPercent: 42,
      rating: 4.9,
      reviewCount: 315,
      imageUrl: "/images/kundli-matching-clean.jpg",
      features: ["Both Charts Analyzed", "Dosha Cancellation Remedies", "Muhurat Guidance", "60 Mins Private Call"],
      durationOrPages: "60 Mins Dedicated",
      badgeText: "Couple Session",
      ctaText: "Book Couple Session",
      ctaLink: "/chat",
      relationType: ExpertProductRelationType.PROVIDER,
      inStock: true,
    },
  ],
};
