import { Tag, TrendingUp, Users, Percent } from "lucide-react";
import type { Coupon } from "@/app/components/coupons/coupon";

export const couponsData: Coupon[] = [
  {
    id: 1,
    code: "ASTRO50",
    description: "50% off on first consultation",
    discountType: "percentage",
    discountValue: 50,
    minOrderValue: 500,
    maxDiscount: 250,
    usageLimit: 100,
    usedCount: 45,
    validFrom: "2024-01-01",
    validUntil: "2024-12-31",
    status: "active",
    createdBy: "Admin",
  },
  {
    id: 2,
    code: "NEWYEAR2024",
    description: "New Year special - ₹300 off",
    discountType: "fixed",
    discountValue: 300,
    minOrderValue: 1000,
    maxDiscount: 300,
    usageLimit: 200,
    usedCount: 187,
    validFrom: "2024-01-01",
    validUntil: "2024-01-31",
    status: "active",
    createdBy: "Admin",
  },
  {
    id: 3,
    code: "WELCOME100",
    description: "Welcome offer for new users",
    discountType: "percentage",
    discountValue: 100,
    minOrderValue: 0,
    maxDiscount: 500,
    usageLimit: 500,
    usedCount: 342,
    validFrom: "2024-01-01",
    validUntil: "2024-06-30",
    status: "active",
    createdBy: "Admin",
  },
  {
    id: 4,
    code: "DIWALI2023",
    description: "Diwali festival offer",
    discountType: "percentage",
    discountValue: 30,
    minOrderValue: 800,
    maxDiscount: 400,
    usageLimit: 150,
    usedCount: 150,
    validFrom: "2023-10-01",
    validUntil: "2023-11-15",
    status: "expired",
    createdBy: "Admin",
  },
  {
    id: 5,
    code: "FLASH20",
    description: "Flash sale - 20% off",
    discountType: "percentage",
    discountValue: 20,
    minOrderValue: 300,
    maxDiscount: 200,
    usageLimit: 50,
    usedCount: 12,
    validFrom: "2024-02-01",
    validUntil: "2024-02-05",
    status: "inactive",
    createdBy: "Admin",
  },
];

export const getStatsConfig = (coupons: Coupon[]) => [
  {
    title: "Total Coupons",
    value: coupons.length,
    icon: Tag,
    iconColor: "text-orange-600",
    iconBgColor: "bg-orange-100",
    trend: { value: "+3", isPositive: true, period: "this month" },
  },
  {
    title: "Active Coupons",
    value: coupons.filter((c) => c.status === "active").length,
    icon: TrendingUp,
    iconColor: "text-green-600",
    iconBgColor: "bg-green-100",
    trend: { value: "67%", isPositive: true, period: "of total" },
  },
  {
    title: "Total Redemptions",
    value: coupons.reduce((sum, c) => sum + c.usedCount, 0),
    icon: Users,
    iconColor: "text-blue-600",
    iconBgColor: "bg-blue-100",
    trend: { value: "+24%", isPositive: true, period: "this week" },
  },
  {
    title: "Avg Discount",
    value: "₹285",
    icon: Percent,
    iconColor: "text-purple-600",
    iconBgColor: "bg-purple-100",
    trend: { value: "+5%", isPositive: true, period: "vs last month" },
  },
];