// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "hero": {
    "badge": "Classic FLAMES Match",
    "titleMain": "FLAMES",
    "titleAccent": "Calculator",
    "paragraph": "Enter two names and discover your fun FLAMES destiny using the classic elimination method."
  },
  "form": {
    "title": "Find Your",
    "titleAccent": "FLAMES Result",
    "boyNameLabel": "Boy Name",
    "boyNamePlaceholder": "Type boy name...",
    "girlNameLabel": "Girl Name",
    "girlNamePlaceholder": "Type girl name...",
    "calculate": "Calculate FLAMES",
    "calculating": "Calculating..."
  },
  "results": {
    "badge": "FLAMES Result",
    "titlePrefix": "Your",
    "possibleInitials": "Result Letter",
    "remainingCount": "Remaining Letters Count:",
    "meanings": {
      "F": {
        "word": "Friends",
        "message": "Strong friendship vibes. Best support system for each other."
      },
      "L": {
        "word": "Love",
        "message": "Romantic energy is high. This match can turn serious."
      },
      "A": {
        "word": "Affection",
        "message": "Caring and emotional bonding is strong between you two."
      },
      "M": {
        "word": "Marriage",
        "message": "Long-term potential is strong. Family-style bonding is seen."
      },
      "E": {
        "word": "Enemy",
        "message": "Too many clashes. Better to avoid ego fights and misunderstandings."
      },
      "S": {
        "word": "Sister",
        "message": "Pure bond and respect. More like a protective connection."
      }
    }
  }
};
export default messages;