// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "hero": {
    "badge": "Real Numerology Calculator",
    "titleMain": "Life Path",
    "titleAccent": "Number",
    "paragraph": "Enter your date of birth to discover your Life Path Number and a quick personality + career hint."
  },
  "form": {
    "title": "Numerology",
    "titleAccent": "Life Path Calculator",
    "dobLabel": "Date of Birth (Required)",
    "calculate": "Calculate Life Path",
    "calculating": "Calculating..."
  },
  "results": {
    "badge": "Your Numerology Result",
    "title": "Life Path",
    "titleAccent": "Number",
    "disclaimer": "Based on Real Numerology Reduction",
    "meanings": {
      "1": {
        "title": "Leader",
        "message": "Independent, strong will, and born to take initiative. Career hint: leadership, business, management."
      },
      "2": {
        "title": "Peace Maker",
        "message": "Emotionally intelligent, supportive, and cooperative. Career hint: counseling, HR, teamwork roles."
      },
      "3": {
        "title": "Creative Soul",
        "message": "Expressive, social, and full of artistic energy. Career hint: media, writing, design, communication."
      },
      "4": {
        "title": "Builder",
        "message": "Practical, disciplined, and stable mindset. Career hint: engineering, planning, operations, systems."
      },
      "5": {
        "title": "Freedom Lover",
        "message": "Adventurous, energetic, and loves change. Career hint: travel, sales, marketing, entrepreneurship."
      },
      "6": {
        "title": "Caretaker",
        "message": "Caring, responsible, and family-focused. Career hint: teaching, healthcare, service-based fields."
      },
      "7": {
        "title": "Spiritual Thinker",
        "message": "Deep thinker, researcher, and spiritually aware. Career hint: analysis, research, IT, psychology."
      },
      "8": {
        "title": "Achiever",
        "message": "Ambitious with strong money/power management energy. Career hint: finance, leadership, corporate growth."
      },
      "9": {
        "title": "Humanitarian",
        "message": "Emotional depth, compassion, and big-hearted nature. Career hint: NGO, healing, public service, arts."
      },
      "11": {
        "title": "Intuitive Visionary",
        "message": "Inspirational, intuitive, and spiritually gifted. Career hint: mentoring, creative leadership, guidance roles."
      },
      "22": {
        "title": "Master Builder",
        "message": "Big achievements, long-term success, and powerful execution. Career hint: large projects, business empires, systems."
      },
      "33": {
        "title": "Compassionate Healer",
        "message": "Teacher energy, healing nature, and strong emotional wisdom. Career hint: spiritual teaching, healing, coaching."
      }
    }
  }
};
export default messages;