// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "hero": {
    "badge": "Name Based Love Match",
    "titleMain": "Love",
    "titleAccent": "Compatibility",
    "paragraph": "Enter two names and reveal a cosmic love percentage with trust, romance, and communication insights."
  },
  "form": {
    "title": "Find Love {percentage} Between",
    "percentage": "%",
    "maleName": "Male Name",
    "malePlaceholder": "Type male name...",
    "femaleName": "Female Name",
    "femalePlaceholder": "Type female name...",
    "calculateBtn": "Calculate Love %",
    "calculating": "Calculating..."
  },
  "results": {
    "badge": "Match Results",
    "title": "Your Love Score",
    "cosmicBond": "Cosmic Bond",
    "breakdownTitle": "Relationship Breakdown",
    "premiumInsight": "Premium Insight",
    "trust": "Trust",
    "romance": "Romance",
    "communication": "Communication",
    "tipTitle": "Tip to strengthen your bond",
    "tipDesc": "Small efforts daily matter more than big promises. Keep communication honest and consistent.",
    "messages": {
      "potential": "This connection has potential. With patience and clear communication, it can grow stronger.",
      "good": "Good match! You both can build trust and create a stable bond with time.",
      "strong": "Strong compatibility! Emotional understanding and attraction are naturally high.",
      "excellent": "Excellent match! Your bond feels deep, supportive, and long-term focused."
    }
  }
};
export default messages;