// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "hero": {
    "badge": "Fun Relationship Prediction",
    "titleMain": "Future",
    "titleAccent": "Timeline",
    "paragraph": "Get a fun prediction for your next 7 days, 30 days, and 6 months based on your names and relationship type."
  },
  "form": {
    "title": "Relationship",
    "titleAccent": "Future",
    "titleSuffix": "Timeline",
    "yourName": "Your Name",
    "partnerName": "Partner Name",
    "namePlaceholder": "Type your name...",
    "partnerPlaceholder": "Type partner name...",
    "relationshipType": "Relationship Type",
    "types": {
      "crush": "Crush",
      "dating": "Dating",
      "married": "Married"
    },
    "calculate": "Generate Timeline",
    "calculating": "Predicting..."
  },
  "results": {
    "badge": "Timeline Report",
    "title": "Relationship",
    "titleAccent": "Forecast",
    "predictionWindow": "Prediction Window",
    "periods": {
      "mood": "Next 7 Days (Mood)",
      "bond": "Next 30 Days (Bond)",
      "stability": "Next 6 Months (Stability)"
    },
    "labels": {
      "low": "Low Phase",
      "balanced": "Balanced",
      "strong": "Strong"
    },
    "messages": {
      "low": "Low phase — avoid misunderstandings, stay calm.",
      "balanced": "Balanced — small efforts will improve the connection.",
      "strong": "Strong — positive growth and smooth bonding ahead."
    },
    "summaries": {
      "needsPatience": "This phase needs patience. Avoid ego clashes and focus on calm communication.",
      "balanced": "A balanced period ahead. Small consistent efforts can make your bond stronger.",
      "strong": "Strong growth is visible. Your connection feels smooth, supportive, and positive."
    }
  }
};
export default messages;