// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "signIn": {
    "title": "Sign In",
    "subtitle": "Access your personalized cosmic insights",
    "brandTitle": "Sign In",
    "brandTo": "to",
    "brandName": "Astrology Bharat",
    "welcome": "Welcome to",
    "noAccount": "No Account?",
    "signUp": "Sign Up",
    "google": "Continue with Google",
    "orEmail": "OR WITH EMAIL",
    "emailLabel": "Email Address",
    "emailPlaceholder": "example@mail.com",
    "passwordLabel": "Password",
    "passwordPlaceholder": "••••••••",
    "forgotPassword": "Forgot Password?",
    "submit": "Sign In Account",
    "signingIn": "Signing In...",
    "errors": {
      "required": "Email and Password are required.",
      "failed": "Sign In failed.",
      "googleFailed": "Google login failed.",
      "unexpected": "An unexpected error occurred."
    },
    "success": "Sign In successful!"
  },
  "signUp": {
    "title": "Sign Up",
    "subtitle": "Create your cosmic account today",
    "welcome": "Welcome to",
    "alreadyAccount": "Already Account?",
    "signIn": "Sign In",
    "google": "Continue with Google",
    "orDetails": "OR REGISTER WITdfgbH DETAILS",
    "fullNameLabel": "Full Name *",
    "fullNamePlaceholder": "Enter Your Full Name",
    "emailLabel": "Email Address *",
    "emailPlaceholder": "Enter Email Address",
    "phoneLabel": "Phone Number *",
    "phonePlaceholder": "10-digit Phone Number",
    "passwordLabel": "Password *",
    "passwordPlaceholder": "••••••••",
    "confirmPasswordLabel": "Confirm Password *",
    "confirmPasswordPlaceholder": "Re-enter Password",
    "submit": "Sign Up Account",
    "creating": "Creating Account...",
    "registering": "Registering your account...",
    "errors": {
      "allFields": "All fields marked * are required.",
      "passLength": "Password must be at least 6 characters long.",
      "passMatch": "Passwords do not match.",
      "phoneInvalid": "Please enter a valid 10-digit phone number.",
      "unexpected": "An unexpected error occurred. Please try again."
    },
    "success": "Registration successful! Please verify your email."
  },
  "forgotPassword": {
    "title": "Forgot Password",
    "subtitle": "Enter your registered email address and we'll send you a link to reset your password.",
    "emailLabel": "Email Address *",
    "emailPlaceholder": "Enter your email",
    "submit": "Send Reset Link",
    "sending": "Sending...",
    "backToSignIn": "Back to Sign In",
    "checkEmail": "Check Your Email",
    "sentMessage": "We have sent a password reset link to {email}. Please check your inbox and click the link to continue.",
    "resend": "Resend Email",
    "errors": {
      "required": "Email is required.",
      "failed": "Failed to send reset link. Please try again.",
      "unexpected": "An unexpected error occurred."
    },
    "success": "Password reset link sent! Please check your email."
  },
  "resetPassword": {
    "title": "Reset Password",
    "subtitle": "Enter your new password below.",
    "passwordLabel": "New Password *",
    "passwordPlaceholder": "Enter New Password",
    "confirmPasswordLabel": "Confirm New Password *",
    "confirmPasswordPlaceholder": "Confirm New Password",
    "submit": "Reset Password",
    "resetting": "Resetting...",
    "successTitle": "Success!",
    "successMessage": "Your password has been reset successfully. Redirecting you to sign in...",
    "goToSignIn": "Go to Sign In Now",
    "errors": {
      "invalidToken": "Invalid or missing reset token.",
      "required": "Password is required.",
      "match": "Passwords do not match.",
      "length": "Password must be at least 6 characters long.",
      "failed": "Failed to reset password. The link may have expired.",
      "unexpected": "An unexpected error occurred."
    }
  },
  "verifyEmail": {
    "title": "Email Verification",
    "verifying": "Verifying your email...",
    "successTitle": "Verification Successful!",
    "successMessage": "Your email has been successfully verified. You can now access all features.",
    "failedTitle": "Verification Failed",
    "failedMessage": "The verification link may be invalid or expired.",
    "goToSignIn": "Go to Sign In",
    "resendTitle": "Need a new link?",
    "resendButton": "Resend Verification Email"
  }
};
export default messages;