export const PATHS = {
  HOME: "/",
  ASTROLOGY: {
    KUNDLI: "/astrology/kundali-matching-by-name",
    HOROSCOPE: "/astrology/horoscope",
    PANCHANG: "/hindu-calendar",
    MUHURAT: "/hindu-calendar",
    CALCULATORS: "/free-services",
    KUNDALI_MATCHING: "/astrology/kundali-matching-by-name",
    NAKSHATRA_MILAN: "/astrology/nakshatra-milan",
    KUNDALI_MATCHING_BY_NAME: "/astrology/kundali-matching-by-name",
    MANGAL_DOSHA: "/astrology/mangal-dosha",
    KAAL_SARP_DOSH: "/astrology/kaal-sarp-dosh",
    LOVE_CALCULATOR: "/astrology/love-calculator",
    SUN_SIGN: "/astrology/sun-sign",
    MOON_SIGN: "/astrology/moon-sign",
    NAKSHATRA: "/astrology/nakshatra",
    ONLINE_PUJA: "/astrology/online-puja",

    CALCULATOR: {
      // FREE CALCULATORS
      PLANET: "/astrology/calculator/planet",
      FLAMES_CALCULATOR: "/astrology/calculator/flames",
      LOVE_COMPATIBILITY_CALCULATOR: "/astrology/calculator/love-compatibility",
      MARRIAGE_AGE_CALCULATOR: "/astrology/calculator/marriage-age",
      SOULMATE_NAME_INITALS_CALCULATOR:
        "/astrology/calculator/soulmate-name-initials",
      LUCKY_NUMBER_CALCULATOR: "/astrology/calculator/lucky-number-color",

      LIFE_PATH_CALCULATOR: "/astrology/calculator/life-path",
      NAME_NUMEROLOGY_CALCULATOR: "/astrology/calculator/name-numerology",
      ZODIAC_SIGN_CALCULATOR: "/astrology/calculator/zodiac-sign-compatibility",
      NAKSHATRA_FINDER: "/astrology/calculator/nakshatra-finder",
      LOYAL_PARTNER_CALCULATOR: "/astrology/calculator/loyal-partner",
      BREAKUP_PATCHUP_CALCULATOR: "/astrology/calculator/breakup-patchup",
      WHO_LOVES_MORE_CALCULATOR: "/astrology/calculator/who-loves-more",
      COMPATIBILITY_BY_ZODIAC_CALCULATOR:
        "/astrology/calculator/compatibility-by-zodiac",
      DAHEJ_CALCULATOR: "/astrology/calculator/dahej",
    },
  },
  EXPERTS: {
    ROOT: "/consultants",
    ASTROLOGERS: "/consultants?category=astrologer",
    NUMEROLOGISTS: "/consultants?category=numerologist",
    VASTU: "/consultants?category=vastu",
    PANDIT: "/consultants?category=pandit",
    PUROHIT: "/consultants?category=purohit",
  },
  CONSULTANTS: {
    ROOT: "/consultants",
    ASTROLOGERS: "/consultants?category=astrologer",
    NUMEROLOGISTS: "/consultants?category=numerologist",
    VASTU: "/consultants?category=vastu",
    PANDIT: "/consultants?category=pandit",
    PUROHIT: "/consultants?category=purohit",
  },
  DEVOTION: {
    ROOT: "/famous-places",
    TEMPLES: "/famous-places",
    LIVE: "/live-darshan",
    RITUALS_PUJA: "/astrology/online-puja",
  },
  PRODUCTS: "/buy-products",
  BUY_PRODUCTS: "/buy-products",
  FREE_SERVICES: "/free-services",
  ONLINE_PUJA: "/astrology/online-puja",
  CART: "/cart",
  CHECKOUT: "/client/checkout",
  PROFILE: "/client/profile",
  LOGIN: "/login",
  SIGN_IN: "/login",
  REGISTER: "/register",
  HELP: "/help",
  SESSION_HISTORY: "/client/session-history",
  FAMOUS_PLACES: "/famous-places",
  BLOG: "/blog",

  PRIVACY_POLICY: "/privacy-policy",
  REFUND_POLICY: "/refund-policy",
  TERMS_AND_CONDITIONS: "/terms-and-conditions",
  COPYRIGHT: "/copyright",

  WALLET: "/client/wallet",
  SETTINGS: "/client/settings",

  // CLIENT DASHBOARD
  DASHBOARD: "/dashboard",
  DASHBOARD_ASTROLOGY: "/dashboard/astrology",
  DASHBOARD_HOROSCOPE: "/dashboard/astrology/horoscope",
  DASHBOARD_KUNDLI: "/dashboard/astrology/kundli",
  DASHBOARD_MATCHING: "/dashboard/astrology/matching",
  DASHBOARD_REPORTS: "/dashboard/astrology/reports",
  DASHBOARD_CONSULTATIONS: "/dashboard/consultations",
  DASHBOARD_EXPERTS: "/dashboard/experts",
  DASHBOARD_ORDERS: "/dashboard/orders",
  DASHBOARD_WALLET: "/dashboard/wallet",
  DASHBOARD_WISHLIST: "/dashboard/wishlist",
  DASHBOARD_NOTIFICATIONS: "/dashboard/notifications",
  DASHBOARD_PROFILE: "/dashboard/profile",
  DASHBOARD_SETTINGS: "/dashboard/settings",

  LIVE_DARSHAN: "/live-darshan",
  HINDU_CALENDAR: "/hindu-calendar",
} as const;
