import { Sparkles, Users, Package, IndianRupee } from "lucide-react";
import type { Service } from "@/app/components/Service/service";

export const servicesData: Service[] = [
  {
    id: 1,
    name: "Birth Chart Reading",
    category: "Vedic Astrology",
    description: "Detailed analysis of your birth chart with predictions",
    duration: 30,
    price: 999,
    discountedPrice: 799,
    status: "active",
    bookings: 156,
    rating: 4.8,
    popularity: "high",
  },
  {
    id: 2,
    name: "Kundli Matching",
    category: "Marriage",
    description: "Comprehensive compatibility analysis for marriage",
    duration: 45,
    price: 1499,
    discountedPrice: 1199,
    status: "active",
    bookings: 243,
    rating: 4.9,
    popularity: "high",
  },
  {
    id: 3,
    name: "Career Consultation",
    category: "Career",
    description: "Get guidance on career path and opportunities",
    duration: 30,
    price: 899,
    discountedPrice: 699,
    status: "active",
    bookings: 98,
    rating: 4.7,
    popularity: "medium",
  },
  {
    id: 4,
    name: "Tarot Reading",
    category: "Tarot",
    description: "3-card or full spread tarot reading session",
    duration: 20,
    price: 599,
    discountedPrice: 499,
    status: "active",
    bookings: 187,
    rating: 4.6,
    popularity: "medium",
  },
  {
    id: 5,
    name: "Numerology Report",
    category: "Numerology",
    description: "Personalized numerology analysis and life path number",
    duration: 25,
    price: 799,
    discountedPrice: 599,
    status: "active",
    bookings: 76,
    rating: 4.5,
    popularity: "low",
  },
  {
    id: 6,
    name: "Love & Relationship Guidance",
    category: "Relationship",
    description: "Astrological guidance for love and relationship issues",
    duration: 30,
    price: 999,
    discountedPrice: 799,
    status: "active",
    bookings: 164,
    rating: 4.8,
    popularity: "high",
  },
  {
    id: 7,
    name: "Health Astrology",
    category: "Health",
    description: "Health predictions and remedies based on birth chart",
    duration: 30,
    price: 1099,
    discountedPrice: 899,
    status: "active",
    bookings: 89,
    rating: 4.6,
    popularity: "medium",
  },
  {
    id: 8,
    name: "Business Astrology",
    category: "Business",
    description: "Astrological advice for business growth and success",
    duration: 45,
    price: 1999,
    discountedPrice: 1599,
    status: "active",
    bookings: 132,
    rating: 4.9,
    popularity: "high",
  },
  {
    id: 9,
    name: "Gemstone Recommendation",
    category: "Remedies",
    description: "Personalized gemstone suggestions with benefits",
    duration: 20,
    price: 699,
    discountedPrice: 499,
    status: "active",
    bookings: 210,
    rating: 4.7,
    popularity: "high",
  },
  {
    id: 10,
    name: "Palm Reading",
    category: "Palmistry",
    description: "Life predictions through detailed palm analysis",
    duration: 25,
    price: 599,
    discountedPrice: 449,
    status: "active",
    bookings: 143,
    rating: 4.5,
    popularity: "medium",
  },
  {
    id: 11,
    name: "Vastu Consultation",
    category: "Vastu",
    description: "Vastu analysis for home or office",
    duration: 40,
    price: 1799,
    discountedPrice: 1399,
    status: "active",
    bookings: 121,
    rating: 4.8,
    popularity: "high",
  },
  {
    id: 12,
    name: "Horoscope Prediction",
    category: "Horoscope",
    description: "Daily, weekly, or monthly horoscope reading",
    duration: 15,
    price: 399,
    discountedPrice: 299,
    status: "active",
    bookings: 265,
    rating: 4.6,
    popularity: "high",
  },
  {
    id: 13,
    name: "Financial Astrology",
    category: "Finance",
    description: "Wealth, savings, and investment predictions",
    duration: 30,
    price: 1299,
    discountedPrice: 999,
    status: "active",
    bookings: 94,
    rating: 4.7,
    popularity: "medium",
  },
  {
    id: 14,
    name: "Child Name Suggestion",
    category: "Naming",
    description: "Astrologically suitable baby name suggestions",
    duration: 20,
    price: 699,
    discountedPrice: 499,
    status: "active",
    bookings: 158,
    rating: 4.8,
    popularity: "medium",
  },
  {
    id: 15,
    name: "Marriage Timing Prediction",
    category: "Marriage",
    description: "Accurate prediction of marriage timing",
    duration: 30,
    price: 1199,
    discountedPrice: 899,
    status: "active",
    bookings: 176,
    rating: 4.9,
    popularity: "high",
  },
  {
    id: 16,
    name: "Spiritual Guidance",
    category: "Spirituality",
    description: "Spiritual path and inner growth guidance",
    duration: 25,
    price: 799,
    discountedPrice: 599,
    status: "active",
    bookings: 83,
    rating: 4.6,
    popularity: "low",
  },
  {
    id: 17,
    name: "Face Reading",
    category: "Physiognomy",
    description: "Personality and future insights through face reading",
    duration: 20,
    price: 699,
    discountedPrice: 499,
    status: "active",
    bookings: 71,
    rating: 4.4,
    popularity: "low",
  },
  {
    id: 18,
    name: "Yearly Prediction Report",
    category: "Prediction",
    description: "Detailed yearly horoscope and life predictions",
    duration: 40,
    price: 1599,
    discountedPrice: 1299,
    status: "active",
    bookings: 134,
    rating: 4.8,
    popularity: "high",
  },
  {
    id: 19,
    name: "Lucky Number & Color",
    category: "Numerology",
    description: "Find your lucky numbers and colors",
    duration: 15,
    price: 499,
    discountedPrice: 349,
    status: "active",
    bookings: 201,
    rating: 4.5,
    popularity: "medium",
  },
  {
    id: 20,
    name: "Remedial Pooja Guidance",
    category: "Remedies",
    description: "Astrological remedies and pooja suggestions",
    duration: 30,
    price: 1399,
    discountedPrice: 1099,
    status: "active",
    bookings: 118,
    rating: 4.7,
    popularity: "medium",
  },
];


export const categories = ["all", "Vedic Astrology", "Marriage", "Career", "Tarot"];

export const getStatsConfig = (services: Service[]) => [
  {
    title: "Total Services",
    value: services.length,
    icon: Package,
    iconColor: "text-orange-600",
    iconBgColor: "bg-orange-100",
    trend: { value: "+2", isPositive: true, period: "this month" },
  },
  {
    title: "Active Services",
    value: services.filter((s) => s.status === "active").length,
    icon: Sparkles,
    iconColor: "text-green-600",
    iconBgColor: "bg-green-100",
    trend: { value: "88%", isPositive: true, period: "of total" },
  },
  {
    title: "Total Bookings",
    value: services.reduce((sum, s) => sum + s.bookings, 0),
    icon: Users,
    iconColor: "text-blue-600",
    iconBgColor: "bg-blue-100",
    trend: { value: "+15%", isPositive: true, period: "this week" },
  },
  {
    title: "Avg Price",
    value: `₹${Math.round(services.reduce((sum, s) => sum + s.price, 0) / services.length)}`,
    icon: IndianRupee,
    iconColor: "text-purple-600",
    iconBgColor: "bg-purple-100",
    trend: { value: "+8%", isPositive: true, period: "vs last month" },
  },
];